/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.Date;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import modelo.Conexion;

/**
 *
 * @author Cristian
 */
public class Alumno extends javax.swing.JFrame {


    
     private static final Pattern REGEXP = Pattern.compile("[0-9]{8}");
     
    Conexion con = new Conexion();
    Connection cn = con.conectar();

    /**
     * Creates new form Alumno
     */
  

    public Alumno() {
        initComponents();
        
        txtID.setVisible(false);
        btnModificarAlumno.setEnabled(false);
        // con este codigo no permito que puedan ingresar texto en el jdatechooser y seleccionen la fecha desde el boton.
        ((JTextField) this.date.getDateEditor()).setEditable(false); 
    }
    
//    public static boolean validarDNI(String dni){
//        return REGEXP.matcher(dni).matches() ;
        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        date = new com.toedter.calendar.JDateChooser();
        txtID = new javax.swing.JTextField();
        btnModificarAlumno = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Alumnos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("sansserif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 80, -1));

        jLabel3.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Apellido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 80, -1));

        jLabel5.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("DNI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 61, -1));

        jLabel6.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Fecha Nac");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 110, -1));
        jPanel1.add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 159, -1));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 159, -1));
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 159, -1));
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 159, -1));

        btnRegistrar.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        btnSalir.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, -1, -1));

        date.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 204, -1));

        txtID.setEditable(false);
        jPanel1.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 49, -1));

        btnModificarAlumno.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        btnModificarAlumno.setText("Modificar");
        btnModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Estado");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 61, -1));

        jLabel4.setFont(new java.awt.Font("Eras Medium ITC", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alumnos");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/63144(achicada).jpg"))); // NOI18N
        jLabel8.setText("Alumno");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 800, 600));

        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        
        //obtengo los valores de los jtextfield y los guardo en variables...
        
        String dni = txtDni.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        //forma de pasar a String el date del JDATECHOOSER!
        String fechaNac = ((JTextField) date.getDateEditor().getUiComponent()).getText();
        String estado = txtEstado.getText();
        
//        validarDNI(dni);
        
        if (dni.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || fechaNac.isEmpty() || estado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "rellene todos los campos");
            
        }else{

        //consulta que va a ser enviada
        String sql = "INSERT INTO alumno (dni,nombre,apellido,fechanacimiento,estado) VALUES (?,?,?,?,?)";
        try {

            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, dni);
            ps.setString(2, nombre);
            ps.setString(3, apellido);
            //seteo Date en la BD parseando el String a Date.  
            ps.setDate(4, Date.valueOf(fechaNac));
            ps.setString(5, estado);

            ps.execute();
            JOptionPane.showMessageDialog(this, "Ingreso Exitoso");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "No se cargó correctamente " + e);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
    }
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Principal p = new Principal();
        p.setVisible(true);
        p.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAlumnoActionPerformed
        
         //obtengo los valores de los jtextfield y los guardo en variables...
        String id = txtID.getText();
        String dni = txtDni.getText();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();

        //forma de pasar a String el date del JDATECHOOSER!
        String fechaNac = ((JTextField) date.getDateEditor().getUiComponent()).getText();

        String estado = txtEstado.getText();
        
        String consulta = "update alumno set dni ='" + dni + "', "
                    + "nombre = '" + nombre + "', apellido = '"+apellido+"', fechaNacimiento = '"+fechaNac+"', estado = '"+estado+"' where idAlumno = '" + id+ "'";
        
        
        try {
            
            PreparedStatement ps = cn.prepareStatement(consulta);

            int indice = ps.executeUpdate();

            if (indice > 0) {

                JOptionPane.showMessageDialog(this, "Datos Actualizados Correctamente");
               
                
            } else {
                JOptionPane.showMessageDialog(this, "No seleccionó ninguna fila");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error " + e);
        }
        

    }//GEN-LAST:event_btnModificarAlumnoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnModificarAlumno;
    public static javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    public static com.toedter.calendar.JDateChooser date;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txtApellido;
    public static javax.swing.JTextField txtDni;
    public static javax.swing.JTextField txtEstado;
    public static javax.swing.JTextField txtID;
    public static javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

    public void borrarFilas(){
        txtID.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEstado.setText("");
        date.setDateFormatString("");
               
    }
}
