/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import static vista.Alumno.date;

/**
 *
 * @author Cristian
 */
public class Principal extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conectar();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        mostrarDatosAlumno();
        mostrarDatosMateria();
        btnModificarAlumno.setVisible(false);
        btnModificarMateria.setVisible(false);
        btnEliminar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMateria = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumno = new javax.swing.JTable();
        btnRegistrarAlumno = new javax.swing.JButton();
        btnRegistrarMate = new javax.swing.JButton();
        btnInscripcion = new javax.swing.JButton();
        btnModificarAlumno = new javax.swing.JButton();
        btnModificarMateria = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtIdMateria = new javax.swing.JTextField();
        jtidAlumno = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor Universidad");
        setBackground(new java.awt.Color(0, 51, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMateriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMateria);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 430, 210));

        tablaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAlumno);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 450, 210));

        btnRegistrarAlumno.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnRegistrarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/alumno.jpg"))); // NOI18N
        btnRegistrarAlumno.setText("Registrar Alumno");
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 290, -1));

        btnRegistrarMate.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrarMate.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnRegistrarMate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/materia.jpg"))); // NOI18N
        btnRegistrarMate.setText("Registrar Materia");
        btnRegistrarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMateActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarMate, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 290, 60));

        btnInscripcion.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inscripcion.jpg"))); // NOI18N
        btnInscripcion.setText(" Inscripción");
        btnInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionActionPerformed(evt);
            }
        });
        getContentPane().add(btnInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 290, 60));

        btnModificarAlumno.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnModificarAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar alumno.jpg"))); // NOI18N
        btnModificarAlumno.setText("Modificar Alumno");
        btnModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAlumnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, 290, -1));

        btnModificarMateria.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnModificarMateria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.jpg"))); // NOI18N
        btnModificarMateria.setText("Modificar Materia");
        btnModificarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMateriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 290, -1));

        btnEliminar.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.jpg"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, 290, 60));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Alumnos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Materias");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, -1, -1));
        getContentPane().add(jtIdMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 670, 30, -1));
        getContentPane().add(jtidAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 670, 30, -1));

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PrincipalUniversidadEjemplo.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed

        Alumno alumno = new Alumno();
        alumno.setVisible(true);
        alumno.setLocationRelativeTo(null);


    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void btnRegistrarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMateActionPerformed
        Materia mat = new Materia();
        mat.setVisible(true);
        mat.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnRegistrarMateActionPerformed

    //Metodo para que al seleccionar una fila de la tabla se desabiliten los botones Registrar alumno
    // y Registrar materia y se habilite el boton Modificar
    private void tablaAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnoMouseClicked
        btnRegistrarAlumno.setEnabled(false);
        btnInscripcion.setEnabled(false);

        btnRegistrarMate.setEnabled(false);
        btnModificarMateria.setVisible(false);
        btnModificarAlumno.setVisible(true);
        btnEliminar.setVisible(true);

        int filaAlumno = tablaAlumno.getSelectedRow();
        this.jtidAlumno.setText((String) tablaAlumno.getValueAt(filaAlumno, 0));
        this.jtIdMateria.setText("");
    }//GEN-LAST:event_tablaAlumnoMouseClicked

    //Metodo para modificar algun dato de la BD
    private void btnModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAlumnoActionPerformed
        try {

            //Guardo en una variable el numero de fila seleccionada
            int fila = tablaAlumno.getSelectedRow();
            // guardo en variables los valores que se encuantran en x fila y x columnas.
            String id = (String) tablaAlumno.getValueAt(fila, 0);
            String dni = (String) tablaAlumno.getValueAt(fila, 1);
            String nombre = (String) tablaAlumno.getValueAt(fila, 2);
            String apellido = (String) tablaAlumno.getValueAt(fila, 3);
//        String fechaNac =(String) tablaAlumno.getValueAt(fila, 4);
            String estado = (String) tablaAlumno.getValueAt(fila, 5);
            //Instancio un formulario y lo hago visible
            Alumno alumno = new Alumno();
            alumno.setVisible(true);
            alumno.setLocationRelativeTo(null);
            alumno.btnRegistrar.setEnabled(false);
            alumno.btnModificarAlumno.setEnabled(true);
            //seteo los datos en los jtextfield de "Alumno"
            alumno.txtID.setText(id);
            alumno.txtDni.setText(dni);
            alumno.txtNombre.setText(nombre);
            alumno.txtApellido.setText(apellido);
//        alumno.date.setDateFormatString(fechaNac);
            alumno.txtEstado.setText(estado);

//        alumno.txtEstado.setText(estado);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "error" + e);

        }


    }//GEN-LAST:event_btnModificarAlumnoActionPerformed

    private void btnInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionActionPerformed
        Inscripcion i = new Inscripcion();
        i.setVisible(true);
        i.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnInscripcionActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        btnModificarAlumno.setVisible(false);
        btnModificarMateria.setVisible(false);
        btnEliminar.setVisible(false);
        btnRegistrarAlumno.setEnabled(true);
        btnRegistrarMate.setEnabled(true);
        btnInscripcion.setEnabled(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tablaMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMateriaMouseClicked
        btnRegistrarAlumno.setEnabled(false);
        btnRegistrarMate.setEnabled(false);
        btnInscripcion.setEnabled(false);
        btnModificarAlumno.setVisible(false);
        btnModificarMateria.setVisible(true);
        btnEliminar.setVisible(true);

        int filaMateria = tablaMateria.getSelectedRow();

        this.jtIdMateria.setText((String) tablaMateria.getValueAt(filaMateria, 0));
        this.jtidAlumno.setText("");

    }//GEN-LAST:event_tablaMateriaMouseClicked

    private void btnModificarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMateriaActionPerformed

        int fila = tablaMateria.getSelectedRow();

        try {
            String id = (String) tablaMateria.getValueAt(fila, 0);
            String nombre = (String) tablaMateria.getValueAt(fila, 1);
            String anio = (String) tablaMateria.getValueAt(fila, 2);
            String estado = (String) tablaMateria.getValueAt(fila, 3);

            Materia mate = new Materia();
            mate.setVisible(true);
            mate.setLocationRelativeTo(null);

            mate.btnRegistrar.setVisible(false);
            mate.btnModificar.setVisible(true);

            mate.txtID.setText(id);
            mate.txtNombre.setText(nombre);
            mate.txtAño.setText(anio);
            mate.txtEstado.setText(estado);

        } catch (Exception e) {
            System.out.println(" error" + e);
        }

    }//GEN-LAST:event_btnModificarMateriaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        if (!this.jtidAlumno.getText().isEmpty()) {

            if (JOptionPane.showConfirmDialog(null, "ESTA SEGURO DE ELIMINAR ALUMNO?", "SALIR", JOptionPane.YES_NO_CANCEL_OPTION) == 0) {
                try {
                    PreparedStatement ps = cn.prepareStatement("DELETE FROM alumno where idAlumno = '" + this.jtidAlumno.getText() + "'");
                    int indice = ps.executeUpdate();
                    if (indice > 0) {
                        mostrarDatosAlumno();

                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "error al eliminar datos");
                }
                JOptionPane.showMessageDialog(this, "Se elimino correctamente");

            } 
        }
        
            if (!this.jtIdMateria.getText().isEmpty()) {

                if (JOptionPane.showConfirmDialog(null, "ESTA SEGURO DE ELIMINAR MATERIA?", "SALIR", JOptionPane.YES_NO_CANCEL_OPTION) == 0) {
                    try {
                        PreparedStatement ps = cn.prepareStatement("DELETE FROM materia where idMateria = '" + this.jtIdMateria.getText() + "'");
                        int indice = ps.executeUpdate();
                        if (indice > 0) {
                            mostrarDatosMateria();

                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(this, "error al eliminar datos");
                    }
                    JOptionPane.showMessageDialog(this, "Se elimino correctamente");

                }
            }
        
    }//GEN-LAST:event_btnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInscripcion;
    public static javax.swing.JButton btnModificarAlumno;
    private javax.swing.JButton btnModificarMateria;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton btnRegistrarMate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtIdMateria;
    private javax.swing.JTextField jtidAlumno;
    public static javax.swing.JTable tablaAlumno;
    private javax.swing.JTable tablaMateria;
    // End of variables declaration//GEN-END:variables

    private void mostrarDatosAlumno() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id Alumno");
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Fecha de Nac");
        modelo.addColumn("estado");
        tablaAlumno.setModel(modelo);
        String consultasql = "select*from alumno";
        String data[] = new String[6];

        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consultasql);
            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                data[5] = rs.getString(6);

                modelo.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar datos " + e);
        }
    }

    private void mostrarDatosMateria() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id Alumno");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");
        modelo.addColumn("Estado");

        tablaMateria.setModel(modelo);
        String consultasql = "select*from materia";
        String data[] = new String[4];

        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consultasql);
            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);

                modelo.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar datos " + e);
        }
    }
}
