/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.sql.Connection;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import static vista.Alumno.date;

/**
 *
 * @author Cristian
 */
public class Principal extends javax.swing.JFrame {

    Conexion con = new Conexion();
    Connection cn = con.conectar();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        mostrarDatosAlumno();
        mostrarDatosMateria();
        btnModificarAlumno.setVisible(false);
        btnModificarMateria.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRegistrarAlumno = new javax.swing.JButton();
        btnRegistrarMate = new javax.swing.JButton();
        btnInscripcion = new javax.swing.JButton();
        btnModificarAlumno = new javax.swing.JButton();
        btnModificarMateria = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlumno = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaMateria = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor Universidad");
        setBackground(new java.awt.Color(0, 51, 153));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registros"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrarAlumno.setText("Registrar Alumno");
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 157, -1));

        btnRegistrarMate.setText("Registrar Materia");
        btnRegistrarMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarMateActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrarMate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 157, -1));

        btnInscripcion.setText("Registrar Inscripción");
        btnInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscripcionActionPerformed(evt);
            }
        });
        jPanel1.add(btnInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 157, -1));

        btnModificarAlumno.setText("Modificar Alumno");
        btnModificarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 140, -1));

        btnModificarMateria.setText("Modificar Materia");
        btnModificarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarMateriaActionPerformed(evt);
            }
        });
        jPanel1.add(btnModificarMateria, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 140, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OIP.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 67, 300, 530));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Alumnos")));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaAlumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaAlumno);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 450, 240));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/759923-minimalism-black-background-digital-art-abstract.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 470, 250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 67, 490, 290));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Materias"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaMateria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMateriaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaMateria);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 200));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/759923-minimalism-black-background-digital-art-abstract.jpg"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 480, 210));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 496, 240));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Walls_iPad_Pro_9.7_015.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 6, 850, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed

        Alumno alumno = new Alumno();
        alumno.setVisible(true);
        alumno.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void btnRegistrarMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMateActionPerformed
        Materia mat = new Materia();
        mat.setVisible(true);
        mat.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_btnRegistrarMateActionPerformed

    //Metodo para que al seleccionar una fila de la tabla se desabiliten los botones Registrar alumno
    // y Registrar materia y se habilite el boton Modificar
    private void tablaAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaAlumnoMouseClicked
        btnRegistrarAlumno.setEnabled(false);
        btnInscripcion.setEnabled(false);
       
        btnRegistrarMate.setEnabled(false);
        btnModificarMateria.setVisible(false);
        btnModificarAlumno.setVisible(true);
    }//GEN-LAST:event_tablaAlumnoMouseClicked

    //Metodo para modificar algun dato de la BD
    private void btnModificarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAlumnoActionPerformed
       try{
           

        //Guardo en una variable el numero de fila seleccionada
        int fila = tablaAlumno.getSelectedRow();
        // guardo en variables los valores que se encuantran en x fila y x columnas.
        String id = (String) tablaAlumno.getValueAt(fila, 0);
        String dni = (String) tablaAlumno.getValueAt(fila, 1);
        String nombre = (String) tablaAlumno.getValueAt(fila, 2);
        String apellido = (String) tablaAlumno.getValueAt(fila, 3);
//        String fechaNac =(String) tablaAlumno.getValueAt(fila, 4);
        String estado = (String) tablaAlumno.getValueAt(fila, 5);
        //Instancio un formulario y lo hago visible
        Alumno alumno = new Alumno();
        alumno.setVisible(true);
        alumno.setLocationRelativeTo(null);
        alumno.btnRegistrar.setEnabled(false);
        alumno.btnModificarAlumno.setEnabled(true);
        //seteo los datos en los jtextfield de "Alumno"
        alumno.txtID.setText(id);
        alumno.txtDni.setText(dni);
        alumno.txtNombre.setText(nombre);
        alumno.txtApellido.setText(apellido);
//        alumno.date.setDateFormatString(fechaNac);
        alumno.txtEstado.setText(estado);
        
        
//        alumno.txtEstado.setText(estado);
       }catch(Exception e){
           JOptionPane.showMessageDialog(this,"error"+ e);
           
       }


    }//GEN-LAST:event_btnModificarAlumnoActionPerformed

    private void btnInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInscripcionActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        btnModificarAlumno.setVisible(false);
        btnModificarMateria.setVisible(false);
        btnRegistrarAlumno.setEnabled(true);
        btnRegistrarMate.setEnabled(true);
        btnInscripcion.setEnabled(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tablaMateriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMateriaMouseClicked
         btnRegistrarAlumno.setEnabled(false);
        btnRegistrarMate.setEnabled(false);
        btnInscripcion.setEnabled(false);
        btnModificarAlumno.setVisible(false);
        btnModificarMateria.setVisible(true);
        
    }//GEN-LAST:event_tablaMateriaMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
          btnModificarAlumno.setVisible(false);
        btnModificarMateria.setVisible(false);
        btnRegistrarAlumno.setEnabled(true);
        btnRegistrarMate.setEnabled(true);
        btnInscripcion.setEnabled(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnModificarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarMateriaActionPerformed
        
        int fila = tablaMateria.getSelectedRow();
        
        try{
        String id = (String)tablaMateria.getValueAt(fila, 0);
        String nombre = (String) tablaMateria.getValueAt(fila, 1);
        String anio = (String) tablaMateria.getValueAt(fila, 2);
        String estado = (String) tablaMateria.getValueAt(fila, 3);
        
        Materia mate = new Materia();
        mate.setVisible(true);
        mate.setLocationRelativeTo(null);
        
        mate.btnRegistrar.setVisible(false);
        mate.btnModificar.setVisible(true);
        
        mate.txtID.setText(id);
        mate.txtNombre.setText(nombre);
        mate.txtAño.setText(anio);
        mate.txtEstado.setText(estado);
        
        }catch(Exception e){
            System.out.println(" error" +e);
        }
        
    }//GEN-LAST:event_btnModificarMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInscripcion;
    public static javax.swing.JButton btnModificarAlumno;
    private javax.swing.JButton btnModificarMateria;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton btnRegistrarMate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tablaAlumno;
    private javax.swing.JTable tablaMateria;
    // End of variables declaration//GEN-END:variables

   private void mostrarDatosAlumno() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id Alumno");
        modelo.addColumn("DNI");
        modelo.addColumn("Nombre");
        modelo.addColumn("Apellido");
        modelo.addColumn("Fecha de Nac");
        modelo.addColumn("estado");
        tablaAlumno.setModel(modelo);
        String consultasql = "select*from alumno";
        String data[] = new String[6];

        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consultasql);
            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);
                data[4] = rs.getString(5);
                data[5] = rs.getString(6);

                modelo.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar datos " + e);
        }
    }

    private void mostrarDatosMateria() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Id Alumno");
        modelo.addColumn("Nombre");
        modelo.addColumn("Año");
        modelo.addColumn("Estado");

        tablaMateria.setModel(modelo);
        String consultasql = "select*from materia";
        String data[] = new String[4];

        Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(consultasql);
            while (rs.next()) {
                data[0] = rs.getString(1);
                data[1] = rs.getString(2);
                data[2] = rs.getString(3);
                data[3] = rs.getString(4);

                modelo.addRow(data);
            }
        } catch (Exception e) {
            System.out.println("Error al mostrar datos " + e);
        }
    }
}
